apiVersion: apps/v1
kind: Deployment
metadata:
  name: HelloWorldDeploy
  labels:
    app: HelloWorldApp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: HelloWorld  #this level will match line number 15 label
  template:
    metadata:
      labels:
        app: HelloWorld
    spec:
      containers:
        - name: HelloWorld
          image: nath2023.azurecr.io/hello-world:latest 
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: HelloWorld-service
spec:
  type: LoadBalancer
  ports:
  - port: 8501
  selector:
    app: HelloWorld
